#pragma once

#define TRAINING_DATA_SIZE 10
#define HIDDEN_LAYER_SIZE 5
#define OUTPUT_LAYER_SIZE 5
#define INPUT_LAYER_SIZE 900
#define IMAGE_WIDTH 30
#define IMAGE_HEIGHT 30
#define NEURON_RADIUS 20
